# Generated by Django 4.2.9 on 2024-04-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_processo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
